---
version: "3"
networks:
  savage-heaven:
    driver: bridge

services:
  webapp:
    container_name: savage_heaven_webapp
    build: webapp
    working_dir: /srv/apps/savage-heaven-webapp
    env_file:
      - savage_heaven.env
    networks:
      - savage-heaven
    volumes:
      - "./volumes/apps:/srv/apps"
    ports:
      - "8000:3000"

  api:
    container_name: savage_heaven_api
    build: api
    working_dir: /srv/apps/savage-heaven-api
    env_file:
      - savage_heaven.env
    networks:
      - savage-heaven
    volumes:
      - "./volumes/apps:/srv/apps"
    ports:
      - "8080:80"

  postgresql:
    container_name: savage_heaven_postgresql
    image: postgres
    env_file:
      - savage_heaven.env
    networks:
      - savage-heaven
    ports:
      - "5432"

  phpgpadmin:
    container_name: savage_heaven_phpgpadmin
    image: zhajor/docker-phppgadmin
    env_file:
      - savage_heaven.env
    networks:
      - savage-heaven
    ports:
      - "9090:80"
      
